version: "3.8"
services :
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  verstand-back:
    image : verstand-back
    ports: 
      - 3000:3000
    depends_on:
      - postgres
